language: java
sudo: false
jdk:
  - openjdk8
notifications:
  email:
    - info@sejda.org
cache:                                                                          
  directories:                                                                  
    - $HOME/.m2     
